[[language]]
name = "markdown"
language-servers = [ "uwu-colors", "marksman" ]

[language-server.uwu-colors]
command = "uwu_colors"

[language-server.marksman]
command = "marksman"

[language.soft-wrap]
enable            = true
max-wrap          = 25
max-indent-retain = 40
wrap-indicator    = "󰘍 "
