name: "Zen Browser"
description: "Browse the Internet"
icon: "󰖟"
command: "zen"
context:
  - name: "New window"
    command: "zen --new-window"
  - name: "New Private window"
    command: "zen --private-window"
