settings:
  autoUpgrade: false

packages:
  brew:
    - "stikypiston/formulae/decree"
    - "stikypiston/formulae/dotkeeper"
    - "stikypiston/formulae/fastcards"
    - "stikypiston/formulae/hocusfocus"
    - "stikypiston/formulae/pricetag"
    - "stikypiston/formulae/recall"
    - "fzf"
    - "fd"
    - "croc"
    - "gum"
    - "soft-serve"
    - "zoxide"
    - "eza"
    - "aerc"
    - "yazi"
    - "gh"
    - "tlrc"
    - "delta"
    - "lazygit"
    - "ncdu"
    - "utftex"
    - "luarocks"
    - "ripgrep"
    - "helix"
    - "starship"
    - "btop"
    - "ruby"
    - "rustup"
    - "bat"
    - "superfile"
    - "fastfetch"
    - "ytsurf"
    - "nushell"
    - "typst"
    - "yamllint"
    - "tree-sitter-cli"
    - "television"
    - "pipes-sh"
    - "lua-language-server"
    - "uv"
    - "pandoc"
    - "luacheck"
    - "pkgx"
    - "just"
    - "glow"
    - "charmbracelet/tap/freeze"
    - "gopls"
    - "yamlfmt"
    - "marksman"
    - "oven-sh/bun/bun"
    - "skate"
    - "zellij"
    - "cabal-install"
    - "haskell-language-server"
  deb:
    - "figlet"
    - "tmux"
    - "libfuse2"
    - "pkg-config"
  go:
    - "github.com/stikypiston/theatre@latest"
    - "github.com/spf13/cobra-cli@latest"
    - "github.com/stikypiston/satchel@latest"
    - "github.com/stikypiston/jots@latest"
