settings:
  autoUpgrade: false

packages:
  brew:
    - "indium114/formulae/decree"
    - "indium114/formulae/dotkeeper"
    - "indium114/formulae/fastcards"
    - "indium114/formulae/hocusfocus"
    - "indium114/formulae/pricetag"
    - "indium114/formulae/recall"
    - "fzf"
    - "fd"
    - "croc"
    - "gum"
    - "zoxide"
    - "eza"
    - "yazi"
    - "gh"
    - "tlrc"
    - "delta"
    - "lazygit"
    - "ncdu"
    - "luarocks"
    - "ripgrep"
    - "helix"
    - "starship"
    - "btop"
    - "ruby"
    - "bat"
    - "fastfetch"
    - "ytsurf"
    - "nushell"
    - "typst"
    - "yamllint"
    - "tree-sitter-cli"
    - "television"
    - "pipes-sh"
    - "lua-language-server"
    - "pandoc"
    - "luacheck"
    - "just"
    - "glow"
    - "charmbracelet/tap/freeze"
    - "gopls"
    - "yamlfmt"
    - "marksman"
    - "jujutsu"
    - "aria2"
    - "nvim"
    - "forgejo-cli"
  deb:
    - "figlet"
    - "tmux"
    - "libfuse2"
    - "pkg-config"
    - "nala"
    - "flatpak"
    - "libssl-dev"
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "zathura"
    - "zathura-pdf-poppler"
    - "zathura-djvu"
    - "vlc"
  go:
    - "github.com/stikypiston/theatre@latest"
    - "github.com/spf13/cobra-cli@latest"
    - "github.com/stikypiston/satchel@latest"
    - "github.com/stikypiston/jots@latest"
