name: "LibreOffice"
description: "Create and edit documents"
icon: ""
command: "libreoffice"
context:
  - name: "Open Base"
    command: "libreoffice --base"
  - name: "Open Calc"
    command: "libreoffice --calc"
  - name: "Open Draw"
    command: "libreoffice --draw"
  - name: "Open Impress"
    command: "libreoffice --impress"
  - name: "Open Math"
    command: "libreoffice --math"
  - name: "Open Writer"
    command: "libreoffice --writer"
