add_newline = false
format = "$directory$git_branch$git_status$nix_shell$character"

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[<](bold red)"

[nix_shell]
format = "[$symbol](bold cyan) "
symbol = "󱄅"
